name: Fix JS styling

on:
  pull_request:
  push:
    branches:
      - main
      - v3

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ./resources/**/*.{js,vue}
          commit_message: "[Chore] Fix styling"
